Python/Django/integration_project/apps/course/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.index),
    url(r'^hit$', views.hit , name='hit'),
    url(r'^remove/(?P<id>\w+)/$', views.remove , name='remove'),
    url(r'^confirm/(?P<id>\w+)/$', views.confirm, name='confirm'),
    url(r'^course_user$', views.course_user, name='course_user'),
    url(r'^add$', views.add, name='add'),
]

Python/Django/integration_project/apps/turtles/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.home),
    url(r'^ninjas$', views.index),
    url(r'^ninjas/(?P<color>\w+)/$', views.turtle)
]

Python/Django/integration_project/integration_project/urls.py
from django.conf.urls import url,include


urlpatterns = [
    url(r'^', include("apps.turtles.urls", namespace="turtles")),
    url(r'^course/', include("apps.course.urls", namespace="course")),
    url(r'^gold/', include("apps.gold.urls", namespace="gold")),
    url(r'^LR/', include("apps.LR.urls", namespace="LR")),
]

Python/Django/integration_project/apps/course/models.py
from django.db import models
from ..LR.models import User
# Create your models here.
class Course(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    creator = models.ManyToManyField(User)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Python/Django/integration_project/apps/multiapps/models.py
from __future__ import unicode_literals
from ..LR.models import User
from django.db import models

# Create your models here.

Python/Django/integration_project/apps/LR/views.py
from django.shortcuts import render,redirect
from .models import User
from django.contrib import messages
# Create your views here.
def index(request):
    return render(request, "LR/index.html")

def register(request):
    viewsResponse = User.objects.ValidForm(request.POST)
    if viewsResponse['isRegistered']:
        request.session['id'] = viewsResponse['user'].id
        request.session['fname'] = viewsResponse['user'].first_name
        return redirect('LR:success')
    else:
        for error in viewsResponse['errors']:
            messages.error(request, error)
        return redirect('LR:index')


def success(request):
    if 'id' not in request.session:
        messages.error(request, 'Must be logged in')
        return redirect('LR:index')
    return render(request, 'LR/success.html')

def login(request):
    viewsResponse = User.objects.login_user(request.POST)
    if viewsResponse['isLoggedIn']:
        request.session['id'] = viewsResponse['user'].id
        request.session['fname'] = viewsResponse['user'].first_name
        return redirect('LR:success')
    else:
        for error in viewsResponse['errors']:
            messages.error(request, error)
        return redirect('LR:index')

def logout(request):
    request.session.clear()
    return redirect('LR:index')

Python/Django/integration_project/apps/course/views.py
from django.shortcuts import render, redirect
from .models import Course
from ..LR.models import User
from django.core.urlresolvers import reverse
# Create your views here.
def index(request):
    context = {
        'name' : Course.objects.all()
    }
    return render(request,"course/index.html", context)

def hit(request):
    if request.method == 'POST':
        Course.objects.create(name = request.POST['name'],
        description = request.POST['description'])
    return redirect('/course')

def remove(reqeust, id):
    context = {
        "name" : Course.objects.get(id=id)
    }
    return render(reqeust,"course/remove.html", context)

def confirm(reqeust, id):
    getid = Course.objects.get(id=id)
    getid.delete()
    return redirect('/course')

def course_user(request):
    context2 ={
        "users" : User.objects.all(),
        "courses" : Course.objects.all()
    }
    return render(request,"course/usercourse.html",context2)

def add(request):
    print "hello"
    if request.method == 'POST':
        print "bye"
        selected_user = User.objects.get(id=request.POST['user'])
        selected_course = Course.objects.get(id=request.POST['course'])
        selected_course.creator.add(selected_user)
        selected_course.save()
    return redirect(reverse('course:course_user'))

Python/Django/integration_project/apps/gold/views.py
from django.shortcuts import render, redirect
import random,time

# Create your views here.
def index(request):
    if not 'total' in request.session:
        request.session['total'] = 0
    if not 'act' in request.session:
        request.session['act'] = []
    return render(request,"gold/game.html")

def run(request):
    places = {
        "farm" : random.randrange(10,20),
        "cave" : random.randrange(5,10),
        "house" : random.randrange(2,5),
        "casino" : random.randrange(-50,50)
        }
    if request.POST["building"] in places:
        renew = places[request.POST["building"]]
        request.session['total'] += renew
        text = {
            "class" : "green" if renew > 0 else "red" ,
            "activity" : "You went {} and {} {} golds".format(request.POST['building'],('lose','earn')[renew >0], renew),
            "clock" : " (" + time.strftime("%Y/%m/%d") + " " + time.strftime("%I:%M %p") + ")"
        }
        request.session['act'].append(text)

        return redirect('/gold')

def reset(request):
    request.session['total'] = 0
    request.session['act'] = []
    return redirect('/gold')
# bolean [ jace, ian ] true = "ian " false = "jace"

Python/Django/integration_project/apps/multiapps/views.py
from django.shortcuts import render

# Create your views here.

Python/Django/integration_project/apps/turtles/views.py
from django.shortcuts import render,redirect

# Create your views here.
def home(request):
    return redirect('/ninjas')

def index(request):
    context = {
        "tmnt":"tmnt.png"
    }
    return render(request,"turtles/index.html",context)

def turtle(request,color):
    if color == "blue":
        context = {
        "tmnt":"leonardo.jpg"
        }
    elif color == "orange":
        context = {
        "tmnt":"michelangelo.jpg"
        }
    elif color == "red":
        context = {
        "tmnt":"raphael.jpg"
        }
    elif color == "purple":
        context = {
        "tmnt":"donatello.jpg"
        }
    else:
        context = {
        "tmnt":"notapril.jpg"
        }
    return render(request,"turtles/index.html",context)

Python/Django/integration_project/apps/course/templates/course/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Courses</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{%static 'course/course.css' %}">
  </head>
  <body>
    <div class="">
      <h2>Add a new course</h2>
      <form class="" action="{% url 'course:hit' %}" method="post">
        {% csrf_token %}
        <label for="name">Name : </label>
        <input type="text" name="name">
        <label for="description">Description:</label>
        <input type="text" name="description">
        <button type="submit" name="submit">Add</button>
      </form>
    </div>
    <div class="">
      <h2>Courses</h2>
        <table>
          <tr>
            <td>Name</td>
            <td>Description</td>
            <td>Date Added</td>
            <td>Actions</td>
          </tr>
            {% for course in name %}
          <tr>
            <td>{{ course.name }}</td>
            <td>{{ course.description }}</td>
            <td>{{ course.created_at }}</td>
            <td><a href="{% url 'course:remove' id=course.id %}">remove</a></td>
          </tr>
            {% endfor %}
      </table>
    </div>
  </body>
</html>

Python/Django/integration_project/apps/course/templates/course/remove.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <h2>Are you sure you want to delete the following course?</h2>
    <p>Name :  {{name.name}}</p>
    <p>Description: {{name.description}}</p>

    <form class="" action="/course">
      {% csrf_token %}
      <button type="submit" name="submit">No</button>
    </form>
    <form action="{% url 'course:confirm' id=name.id %}">
      {% csrf_token %}
      <button type="submit" name="submit"> Yes I want to delete this</button>
    </form>
  </body>
</html>

Python/Django/integration_project/apps/course/templates/course/usercourse.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="">
      <form class="" action="{% url 'course:add' %}" method="post">
        {% csrf_token %}
        <select class="" name="user">
          {% for user in users %}
          <option value="{{user.id}}">{{user.first_name}}</option>
          {% endfor %}
        </select>
        <select class="" name="course">
          {% for course in courses %}
          <option value="{{course.id}}">{{ course.name }}</option>
          {% endfor %}
        </select>
        <button type="submit" name="submit">Add user To Course</button>
      </form>
    </div>
    <br>
    <div class="">
      <table>
        <tr>
          <td>Couse</td>
          <td>Title</td>
          <td>Number of Users</td>
        </tr>
        <br>
        {% for course in courses %}
        <tr>
          <td>{{ course.name }}</td>
          <td>{{ course.description }}</td>
          <td>{{ course.creator.count }}</td>
          {% endfor %}
        </tr>
      </table>
    </div>
  </body>
</html>

Python/Django/integration_project/apps/turtles/templates/turtles/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    {% load staticfiles %}
  </head>
  <body>
    <img src= {% static "img/"|add:tmnt %}>
    <!-- <img src= {% static "turtles/"} alt=""> -->
  </body>
</html>