Python/Django/beltReview/apps/LR/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.index , name ="index"),
    url(r'^register$', views.register, name ="register"),
    url(r'^success$', views.success, name ="success"),
    url(r'^login$', views.login, name ="login"),
    url(r'^logout$', views.logout, name="logout"),
]

Python/Django/beltReview/apps/bookreview/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.index, name="home"),
    url(r'^add$', views.add, name="add"),
    url(r'^logout$', views.logout, name="logout"),
    url(r'^create$', views.create, name="create"),
    url(r'^review$', views.review, name="review"),
    url(r'^user$', views.user, name="user"),
]

Python/Django/beltReview/beltReview/urls.py
from django.conf.urls import url,include

urlpatterns = [
    url(r'^', include("apps.LR.urls", namespace="home")),
    url(r'^book/', include("apps.bookreview.urls", namespace="book")),
]

Python/Django/beltReview/apps/LR/models.py
from django.db import models
import re,bcrypt
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
NAME_REGEX = re.compile(r'^[a-zA-Z]$')
# Create your models here.

class UserManager(models.Manager):
    def ValidForm(self, userData):
        errors = []
        if not userData['first_name'].isalpha():
            errors.append('First name should be characters')
        if not len(userData['last_name']):
            errors.append('Last name is required')
        if not userData['last_name'].isalpha():
            errors.append('Last name should be characters')
        if not len(userData['email']):
            errors.append('Email required!')
        if not EMAIL_REGEX.match(userData['email']):
            errors.append('Invalid Email!')
        check_email = self.filter(email = userData['email'])
        if check_email:
            errors.append('Sorry .. Email is already exists!')
        if not len(userData['password']):
            errors.append('Please enter the Password')
        if len(userData['password']) < 8:
            errors.append('Password must be at least 8 long')
        if not userData['password'] == userData['confirm']:
            errors.append('Passwords must match!')

        modelsResponse = {}

        if errors:
            modelsResponse['isRegistered'] = False
            modelsResponse['errors'] = errors
        else:
            hashed_password = bcrypt.hashpw(userData['password'].encode(), bcrypt.gensalt())
            user = self.create(first_name = userData['first_name'], last_name = userData['last_name'], email = userData['email'], password = hashed_password)
            modelsResponse['isRegistered'] = True
            modelsResponse['user'] = user

        return modelsResponse

    def login_user(self, userData):
        user = self.filter(email = userData['email'])
        errors = []
        modelsResponse = {}
        if not user:
            errors.append('Invalid email')
        else:
            if bcrypt.checkpw(userData['password'].encode(), user[0].password.encode()):
                modelsResponse['isLoggedIn'] = True
                modelsResponse['user'] = user[0]

            else:
                errors.append('Email or Password is not correct')

        if errors:
            modelsResponse['isLoggedIn'] = False
            modelsResponse['errors'] = errors

        return modelsResponse


class User(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField()
    password = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()

Python/Django/beltReview/apps/bookreview/models.py
from __future__ import unicode_literals
from ..LR.models import User
from django.db import models

class BookManager(models.Manager):
    def add_book(self, userData):
        errors = []
        selected_authorlist = userData['authorlist']
        if not len(userData['title']):
            errors.append('Title cannot be blank')
        if not len(userData['review']):
            errors.append('Please tell me about the book')
        if selected_authorlist == 'none':
            if not len(userData['newauthor']):
                errors.append('Select the author from list or put the your author please')
        if not selected_authorlist == 'none':
            if len(userData['newauthor']):
                errors.append('You already selected author you cannot put the new author')
        if len(userData['review']) < 5:
            errors.append('Your Review is too short')

        check_author = self.filter(newauthor = userData['newauthor'])

        if check_author:
            errors.append('Your author is already exsist on list')

        modelsResponse = {}

        if errors:
            modelsResponse['isRegistered'] = False
            modelsResponse['errors'] = errors

        else:
            if len(userData['newauthor']):
                book = self.create(title = userData['title'], newauthor = userData['newauthor'], review = userData['review'], rating = userData['rating'])
                modelsResponse['isRegistered'] = True
                modelsResponse['book'] = book

            if not len(userData['newauthor']):
                book = self.create(title = userData['title'], newauthor = userData['authorlist'], review = userData['review'], rating = userData['rating'])
                modelsResponse['isRegistered'] = True
                modelsResponse['book'] = book

        return modelsResponse

# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=50)
    rating = models.IntegerField()
    review = models.TextField()
    user = models.ManyToManyField(User, related_name="created_by")
    newauthor = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = BookManager()

Python/Django/beltReview/apps/LR/views.py
from django.shortcuts import render,redirect
from .models import User
from django.contrib import messages
# Create your views here.
def index(request):
    return render(request, "LR/index.html")

def register(request):
    viewsResponse = User.objects.ValidForm(request.POST)
    if viewsResponse['isRegistered']:
        request.session['id'] = viewsResponse['user'].id
        request.session['fname'] = viewsResponse['user'].first_name
        return redirect('book:home')
    else:
        for error in viewsResponse['errors']:
            messages.error(request, error)
        return redirect('home:index')


def success(request):
    if 'id' not in request.session:
        messages.error(request, 'Must be logged in')
        return redirect('book:home')
    return render(request, 'LR/success.html')

def login(request):
    viewsResponse = User.objects.login_user(request.POST)
    if viewsResponse['isLoggedIn']:
        request.session['id'] = viewsResponse['user'].id
        request.session['fname'] = viewsResponse['user'].first_name
        return redirect('book:home')
    else:
        for error in viewsResponse['errors']:
            messages.error(request, error)
        return redirect('home:index')

def logout(request):
    request.session.clear()
    return redirect('home:index')

Python/Django/beltReview/apps/bookreview/views.py
from django.shortcuts import render,redirect
from ..LR.models import User
from .models import Book
from django.contrib import messages
# Create your views here.
def index(request):
    context = {
        "books" : Book.objects.all(),
        "users" : User.objects.all(),
    }
    if 'id' not in request.session:
        messages.error(request, 'Must be logged in')
        return redirect('home:index')
    return render(request,"bookreview/home.html",context)

def add(request):
    context = {
        "books" : Book.objects.all()
    }
    return render(request,"bookreview/add.html",context)

def logout(request):
    request.session.clear()
    return redirect('home:index')

def create(request):

    if request.method == 'POST':
        viewsResponse = Book.objects.add_book(request.POST)

        if viewsResponse['isRegistered']:
            return redirect('book:review')

        else:
            for error in viewsResponse['errors']:
                messages.error(request, error)
                return redirect('book:add')

def review(request):
    context = {
        "books" : Book.objects.all(),
        "users" : User.objects.all(),
    }
    return render(request, "bookreview/review.html",context)

def user(request):
    context = {
        "users" : User.objects.all()
    }
    return render(request, "bookreview/user.html", context)

Python/Django/beltReview/apps/bookreview/templates/bookreview/add.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="">
      <a href="{% url 'book:home' %}">home</a>
      <a href="{% url 'book:logout' %}">Logout</a>
      <h2>Add a New Book Title and a Review:</h2>
    </div> <a href="#"></a>
    <form class="" action="{% url 'book:create' %}" method="post">
      {% csrf_token %}
      <label for="title">Book Title: </label>
      <input type="text" name="title" value="">
      <br>
      <label for="authorlist">Choose from the list :</label>
      <select class="" name="authorlist">
        <option value="none">Select Author</option>
        <optgroup label="Jace's Recommend Authors">
          <option value="jace">Jace waitforit King</option>
          <option value="taylor">Taylor Jr</option>
          <option value="ian">Iam Ian</option>
        </optgroup>
        <optgroup label="Authors created by users">
          {% for book in books %}
          <option value="{{ book.id }}">{{book.newauthor}}</option>
          {% endfor %}
        </optgroup>
      </select>
      <br>
      <label for="newauthor">Or add a new author:</label>
      <input type="text" name="newauthor">
      <br>
      <label for="review">Review:</label>
      <input style="width:500px; height:100px;"type="text" name="review" value="">
      <br>
      <p><label for="rating">Rating : </label><select class="" name="rating">
        <option value="5">5</option>
        <option value="4">4</option>
        <option value="3">3</option>
        <option value="2">2</option>
        <option value="1">1</option>
      </select> stars</p>
      <button type="submit" name="submit">Add Book and reviews</button>
    </form>
    {% if messages %}
      {% for message in messages %}
        <p style="color:red">{{message}}</p>
      {% endfor %}
    {% endif %}
  </body>
</html>

Python/Django/beltReview/apps/bookreview/templates/bookreview/home.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <style media="screen">
      #logout
      {
        color:white;
        background-color: green;
      }
      .review{
        border: 2px solid lightblue;
        max-width: 500px;
      }
      #add
      {
        margin-left: 300px;
        margin-right: 15px;
      }
      .rate
      {
        font-family: fantasy;
        color:yellow;
        background-color: black;
        max-width: 95px;
        text-align: center;
      }
    </style>
  </head>
  <body>
    <div class="">
      <h1>Welcome, {{request.session.fname}}</h1>
      <a id = "add" href="{% url 'book:add'%}">add book and author</a>
      <a href="{% url 'book:logout' %}"><button id="logout" type="submit" name="submit">Logout</button></a>
    </div>
    <h2>Recent Book Reviews:</h2>
    <div class="review">
      {% for book in books%}
      <div class="">
        <h2>Title :<a href="{% url 'book:review' %}">{{book.title}}</a></h3>
          {% for user in users%}
        <h3>Author : {{book.newauthor}}</h3>
        <h3>Created by : <a href="{% url 'book:user' %}">{{user.first_name}}{{user.last_name}}{{user.id}}</a></h2>
          {% endfor %}
        <h3 class="rate">Rating : {{book.rating}}</h3>
        <h4>Review : {{book.review}}</h4>
        <br>
        {% endfor %}
    </div>
  </body>
</html>

Python/Django/beltReview/apps/bookreview/templates/bookreview/review.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <a href="{% url 'book:home' %}">Home</a>
    <h2>Review</h2>
    {% for book in books%}
    <div class="">
      <h2><a href="{% url 'book:review' %}"></a>{{book.title}}</h3>
        {% for user in users%}
        <h3>{{book.newauthor}}</h3>
      <h3><a href="{% url 'book:user' %}">{{user.first_name}}{{user.last_name}}{{user.id}}</a></h2>
        {% endfor %}
      <h2>{{book.rating}}</h2>
      <h4>{{book.review}}</h4>
      <br>
      {% endfor %}
    </div>
  </body>
</html>

Python/Django/beltReview/apps/bookreview/templates/bookreview/user.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>User Info</title>
  </head>
  <body>
    {% for user in users%}
    <h2>{{user.fname}} {{user.lname}}</h2>
    {% endfor %}
  </body>
</html>