Python/Django/BeltExam/BeltExam/urls.py
from django.conf.urls import url,include

urlpatterns = [
    url(r'^', include("apps.LR.urls", namespace="home")),
    url(r'^dashboard/', include("apps.belt.urls", namespace="belt")),
]

Python/Django/BeltExam/apps/LR/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.index , name ="index"),
    url(r'^register$', views.register, name ="register"),
    url(r'^success$', views.success, name ="success"),
    url(r'^login$', views.login, name ="login"),
    url(r'^logout$', views.logout, name="logout"),
    url(r'^main$', views.main, name="main"),
]

Python/Django/BeltExam/apps/belt/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="main"),
    url(r'^logout$', views.logout, name="logout"),
    url(r'^add$', views.add, name="add"),
    url(r'^additem$', views.additem, name="additem"),
    url(r'^addwish/(?P<id>\w+)/$', views.addwish, name="addwish"),
    url(r'^delte/(?P<id>\w+)/$', views.delete, name="delete"),
    url(r'^deletelist/(?P<id>\w+)/$', views.deletelist, name="deletelist"),
    url(r'^info/(?P<id>\w+)/$', views.info, name="info"),
]

Python/Django/BeltExam/apps/LR/models.py
from django.db import models
from datetime import date
import re,bcrypt
# Create your models here.

class UserManager(models.Manager):
    def ValidForm(self, userData):
        errors = []
        if not userData['name'].isalpha():
            errors.append('Your name should be characters')
        if len(userData['name']) < 3:
            errors.append('Name must be at least 3 characters')
        if len(userData['username']) < 3:
            errors.append('Username must be at least 3 characters!')
        check_username = self.filter(username = userData['username'])
        if check_username:
            errors.append('Sorry .. Your Username is already exists!')
        if not len(userData['password']):
            errors.append('Please enter the Password')
        if len(userData['password']) < 8:
            errors.append('Password must be at least 8 long')
        if not userData['password'] == userData['confirm']:
            errors.append('Passwords must match!')


        modelsResponse = {}

        if errors:
            modelsResponse['isRegistered'] = False
            modelsResponse['errors'] = errors
        else:
            hashed_password = bcrypt.hashpw(userData['password'].encode(), bcrypt.gensalt())
            user = self.create(name = userData['name'],username = userData['username'], password = hashed_password)
            modelsResponse['isRegistered'] = True
            modelsResponse['user'] = user

        return modelsResponse

    def login_user(self, userData):
        user = self.filter(username = userData['username'])
        errors = []
        modelsResponse = {}
        if not user:
            errors.append('Invalid username')
        else:
            if bcrypt.checkpw(userData['password'].encode(), user[0].password.encode()):
                modelsResponse['isLoggedIn'] = True
                modelsResponse['user'] = user[0]

            else:
                errors.append('Username or Password is not correct')

        if errors:
            modelsResponse['isLoggedIn'] = False
            modelsResponse['errors'] = errors

        return modelsResponse


class User(models.Model):
    name = models.CharField(max_length=200)
    username = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()

Python/Django/BeltExam/apps/belt/models.py
from django.db import models
from ..LR.models import User

class ItemManager(models.Manager):
    def post_item(self, Item, user_id):
        errors = []
        if len(Item['item']) < 3 :
            errors.append("Item name must be at least 3 characters")
        check_item = self.filter(itemname = Item['item'])
        if check_item:
            errors.append("Your Item is already in list")

        modelsResponse = {}

        if errors:
            modelsResponse['isRegistered'] = False
            modelsResponse['errors'] = errors

        else:
            LoginUser = User.objects.get(id=user_id)
            item = self.create(itemname = Item['item'], creator = LoginUser)
            modelsResponse['isRegistered'] = True
            modelsResponse['item'] = item

        return modelsResponse

    def delete_item(self, item_id):
        item_delete = Item.objects.get(id=item_id)
        item_delete.delete()

    def remove_wish(self, wish_id):
        user_wish = Item.objects.get(id=wish_id)
        user_wish.wishlist.clear()

    def add_wish(self, wishitem, user_id):
        LoginUser= User.objects.get(id=user_id)
        user_wish = wishitem
        user_wish.wishlist.add(LoginUser)
        user_wish.save()

# Create your models here.
class Item(models.Model):
    itemname = models.CharField(max_length=200)
    creator = models.ForeignKey(User, related_name="User_Items")
    wishlist = models.ManyToManyField(User, related_name="user_wishs")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ItemManager()

Python/Django/BeltExam/apps/LR/views.py
from django.shortcuts import render,redirect
from .models import User
from django.contrib import messages
# Create your views here.
def index(request):
    return redirect("home:main")

def main(request):
    return render(request, "LR/index.html")

def register(request):
    viewsResponse = User.objects.ValidForm(request.POST)
    if viewsResponse['isRegistered']:
        request.session['id'] = viewsResponse['user'].id
        request.session['name'] = viewsResponse['user'].name
        return redirect('belt:main')
    else:
        for error in viewsResponse['errors']:
            messages.error(request, error)
        return redirect('home:index')


def success(request):
    if 'id' not in request.session:
        messages.error(request, 'Must be logged in')
        return redirect('home:index')

def login(request):
    viewsResponse = User.objects.login_user(request.POST)
    if viewsResponse['isLoggedIn']:
        request.session['id'] = viewsResponse['user'].id
        request.session['name'] = viewsResponse['user'].name
        return redirect('belt:main')
    else:
        for error in viewsResponse['errors']:
            messages.error(request, error)
        return redirect('home:index')

def logout(request):
    request.session.clear()
    return redirect('home:index')

Python/Django/BeltExam/apps/belt/views.py
from django.shortcuts import render,redirect
from ..LR.models import User
from .models import Item
from django.contrib import messages
# Create your views here.
def index(request):
    if 'id' not in request.session:
        messages.error(request, 'Must be logged in')
        return redirect('home:index')
    else:
        context = {
            "items" : Item.objects.filter(wishlist__id=request.session['id']),
            "users" : User.objects.all(),
            "otheritems" : Item.objects.exclude(wishlist__id=request.session['id'])
        }
        return render(request, "belt/main.html", context)

def logout(request):
    request.session.clear()
    return redirect('home:index')

def add(request):
    return render(request, "belt/add.html")

def additem(request, id):
    viewsResponse = Item.objects.post_item(request.POST, request.session["id"])
    if viewsResponse['isRegistered']:
        request.session['item'] = viewsResponse['item'].itemname
        wish_id = Item.objects.get(id=id)
        Item.objects.add_wish(wish_id, request.session["id"])
        return redirect('belt:main')
    else:
        for error in viewsResponse['errors']:
            messages.error(request, error)
        return redirect('belt:add')
def delete(request, id):
    item_id = id
    Item.objects.delete_item(item_id)
    return redirect('belt:main')

def addwish(request, id):
    wish_id = Item.objects.get(id=id)
    Item.objects.add_wish(wish_id, request.session["id"])
    return redirect('belt:main')

def deletelist(request,id):
    wish_id = id
    Item.objects.delete_item(wish_id)
    return redirect('belt:main')

def info(request,id):
    wish_id = id
    context = {
        "lists": Item.objects.filter(wishlist__id=request.session["id"]),
        "users": User.objects.filter(user_wishs__id=wish_id),
        "wish": Item.objects.get(id=wish_id),
    }
    return render(request, "belt/info.html", context)

Python/Django/BeltExam/apps/LR/templates/LR/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="Regi">
      {% if messages %}
        {% for message in messages %}
        <p>{{message}}</p>
        {% endfor %}
      {% endif %}
      <h1>Registration</h1>
      <form class="" action="{% url 'home:register' %}" method="post">
        {% csrf_token %}
        <label for="name">Name : </label>
        <input type="text" name="name">
        <label for="username">Username : </label>
        <input type="text" name="username">
        <label for="password">Password : </label>
        <input type="password" name="password">
        <label for="confirm">Confirm pw : </label>
        <input type="password" name="confirm">

        <button type="submit" name="submit">Register</button>
      </form>
    </div>
    <div class="">
      <h1>Login !</h1>
      <form action="{% url 'home:login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username : </label>
        <input type="text" name="username" value="">
        <label for="password">Password: </label>
        <input type="password" name="password" value="">
        <button type="submit" name="submit">Log In</button>
      </form>
    </div>

  </body>
</html>

Python/Django/BeltExam/apps/LR/templates/LR/success.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome, {{ request.session.fname}}</h1>
    <form class="" action="{% url 'home:logout' %}" method="post">
      {% csrf_token %}
      <input type="submit" name="" value="Logout">

    </form>
  </body>
</html>

Python/Django/BeltExam/apps/belt/templates/belt/add.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Create a New Wish List Item</h1>
    <a href="{% url 'belt:main'%}">home</a>
    <a href="{% url 'belt:logout'%}"><button type="submit" name="logout">Logout</button></a>
    <form class="" action="{% url 'belt:additem'%}" method="post">
      {% csrf_token %}
      <label for="item">Item/Product</label>
      <input type="text" name="item">
      <button type="submit" name="submit">Add</button>
    </form>
    {% if messages %}
      {% for message in messages %}
      <p>{{message}}</p>
      {% endfor %}
    {% endif %}
  </body>
</html>

Python/Django/BeltExam/apps/belt/templates/belt/info.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% for info in lists%}
      <h2>{{info.itemname}}</h2>
    {% endfor %}

    <h4>Users who added this product/item under their wish list:</h4>
    {% for user in users %}
      <p>{{ user.first_name }}</p>
    {% endfor %}

  </body>
</html>

Python/Django/BeltExam/apps/belt/templates/belt/main.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h2>Hi {{request.session.name}}!</h2>
    <a href="{% url 'belt:logout'%}"><button type="submit" name="logout">Logout</button></a>
    <a href="{% url 'belt:add'%}">Add Item</a>

    <div class="">
      <h2>My WishList</h2>
      <table>
        <tr>
        <td>Item</td>
        <td>Added by</td>
        <td>Date Added</td>
        <td>Action</td>
        </tr>
        <br>
          {% for item in items %}
          <tr>
            <td><a href="{% url 'belt:info' id=item.id%}">{{ item.itemname }}</a></td>
            <td>{{ item.creator.name }}</td>
            <td>{{ item.created_at }}</td>
            <td>
              {% if item.creator.id == request.session.id %}
                <a href="{% url 'belt:delete' id=item.id%}">Delete</a>
              {% else %}
                <a href="{% url 'belt:deletelist' id=item.id%}">Remove from my Wishlist</a>
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </table>
    </div>
    <div class="">
      <h2>Other User's Wishlist</h2>
      <table>
        <tr>
        <td>Item</td>
        <td>Added by</td>
        <td>Date Added</td>
        <td>Action</td>
        </tr>
        <br>
          {% for item in otheritems %}
          <tr>
            <td><a href="{% url 'belt:info' id=item.id%}">{{ item.itemname }}</a></td>
            <td>{{ item.creator.name }}</td>
            <td>{{ item.created_at }}</td>
            <td>
              <a href="{% url 'belt:addwish' id=item.id%}">Add to my Wishilist</a>
            </td>
          {% endfor %}
          </tr>
        </table>
    </div>
  </body>
</html>